### ISSUE TITLE
第一次编译后访问页面 点击菜单页面会出现空白 然后才加载出页面数据

### ISSUE THREAD

**Issue by ma4297263** [Daymychen/art-design-pro#10]

**Comment by HAOSunny** [comment]
![1728567426776](https://github.com/user-attachments/assets/94c29fa3-970d-4cde-a930-c7e8ac6a8e18)
当我切换菜单管理的时候，会白屏一段时间，然后出现数据

**Comment by HAOSunny** [comment]
> _No description provided._

我也遇到了同样的情况

**Comment by Daymychen** [comment]
问题已解决
