### ISSUE TITLE
当一个组件里面使用mounted或者$nextTick函数时，刷新界面会发送两个一样的请求

### ISSUE THREAD

**Issue by sm0tl39r** [Daymychen/art-design-pro#4]
问题：当一个组件里面使用mounted或者$nextTick函数时，刷新界面会发送两个一样的请求，如果在请求拦截里面做防重提示的话，每次刷新都会触发提示。
原因：
1、刷新的时候会触发一次组件的mounted或者$nextTick函数请求接口一次
2、初始化出题的时候，在【src/views/index】里面监听了【refresh】导致调用realod方法再一次刷新一次界面
所以请求两次大概是这么猜的
<img width="893" alt="image" src="https://github.com/user-attachments/assets/77912a77-1b09-44dc-ae9d-62cd2eb4c4a3">

**Comment by Daymychen** [comment]
修复好了
