### ISSUE TITLE
项目启动控制台报错，希望有时间能优化下，提升体验

### ISSUE THREAD

**Issue by sm0tl39r** [Daymychen/art-design-pro#7]
1、
<img width="770" alt="image" src="https://github.com/user-attachments/assets/44604ae5-53dd-4105-a720-22cdede5eb1f">
2、
<img width="914" alt="image" src="https://github.com/user-attachments/assets/939cbb45-db97-493a-937c-2d5ffdd000ea">

**Comment by Daymychen** [comment]
已修复

**Comment by sm0tl39r** [comment]
为啥我跑main分支，还是报错
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/cc246e04-a477-4e44-b83a-4d7310665a50">

**Comment by Daymychen** [comment]
我这边刚拉下来是正常的，估计可能是安装依赖有问题，你这边是用 pnpm 安装的依赖吗？
￼

**Comment by sm0tl39r** [comment]
用的是cnpm

**Comment by sm0tl39r** [comment]
使用pnpm重新安装 一下依赖就正常了

**Comment by sm0tl39r** [comment]
但是首次打开，登录界面有点慢

**Comment by Daymychen** [comment]
好的，你加一下我微信吧，邮件沟通效率太低了，微信号：jDdi1314。
