### ISSUE TITLE
启动后出现Deprecation Warning: red() is deprecated. Suggestion:  color.channel($color, "red", $space: rgb)

### ISSUE THREAD

**Issue by ma4297263** [Daymychen/art-design-pro#9]
More info: https://sass-lang.com/d/color-functions

   ╷
52 │     #{red($color),
   │       ^^^^^^^^^^^
   ╵
    node_modules\.pnpm\element-plus@2.8.4_vue@3.5.10\node_modules\element-plus\theme-chalk\src\mixins\_var.scss 52:7  set-css-color-rgb()        
    node_modules\.pnpm\element-plus@2.8.4_vue@3.5.10\node_modules\element-plus\theme-chalk\src\var.scss 17:5          @use
    node_modules\.pnpm\element-plus@2.8.4_vue@3.5.10\node_modules\element-plus\theme-chalk\src\base.scss 1:1          @use
    node_modules\.pnpm\element-plus@2.8.4_vue@3.5.10\node_modules\element-plus\theme-chalk\src\index.scss 1:1         @use
    src\assets\styles\element.scss 26:1                                                                               root stylesheet

Deprecation Warning: green() is deprecated. Suggestion:

**Comment by Daymychen** [comment]
使用 pnpm 安装依赖可以解决
https://www.lingchen.kim/art-design-pro/docs/guide/quick-start.html
